project:
  type: book
  output-dir: _book
  resources: .htaccess

#title-block-banner: banner_stat.png
#title-block-banner-color: "#093162"
book:
  google-analytics: "G-MZSGY1VSFE"
  cookie-consent:
    type: express
    style: simple
    palette: light
  title: "STAT 404 | Style Guide"
  favicon: assets/favicon.ico
  page-navigation: true
  sidebar:
    style: "docked"
    logo: PSU_Ecosshield.png
    logo-href: "https://science.psu.edu"
    search: true #search window on the left nav
    contents: auto #this is to create the nav from the files automatically, but it doesn't appear to be working
  navbar:
    background: "#001E44" # this is 'nittany navy'
    foreground: "light"
    right:
      - text: "Department of Statistics"
        url: https://science.psu.edu/stat


  search:
    location: sidebar
  reader-mode: true
  site-url: https://dev.stat.psu.edu/quarto501. #I don't know if this works


  back-to-top-navigation: true
  chapters:
    - index.qmd
    - part: "Lessons"
      chapters:
        - basic_formatting.qmd
        - Links.qmd
        - layout.qmd
        - tables.qmd
        - Components.qmd
        - equations.qmd
        - figures.qmd
        - Video.qmd
        - code.qmd
        - Sample_lesson.qmd
        - interactives.qmd
    - part: "Resources"
      chapters:
        - resources.qmd
        - yamlcode.qmd
        - SAStest.qmd


  ## Use <br> to make a new line in the footer
  page-footer:
    background: light
    left: |
      Except where otherwise noted, content on this site is licensed under a [CC BY-NC 4.0](https://creativecommons.org/licenses/by-nc/4.0/) license.<br><br>
      ![BYNC](assets/by-nc.svg)
    center: "[OPEN.ED@PSU](https://oer.psu.edu/)"
    right: "[Privacy](https://www.psu.edu/web-privacy-statement/) | [Accessiblity](https://www.psu.edu/accessibilitystatement/) | [Copyright](https://www.psu.edu/copyright-information/) <br>
      [The Pennsylvania State University &copy; 2024](https://www.psu.edu/) | <br> [Leave Us Feedback](https://forms.office.com/r/GbC8H0pZhm)"

downloads: [pdf]

website:
  draft-mode: gone


format:
  html:
    toc: true
    toc-title: In this lesson
    code-tools: true  #only while Prabhani reviews..false when live to students
    code-overflow: wrap
    #mainfont: "Arial" #sets the font type
    fontsize: 1.1rem #sets the font size
    linestretch: 1.5 #sets distance between lines in pargraphs
    theme:
      light: [flatly, lightCustom.scss]
      dark: [darkly, darkCustom.scss]
    grid:
      content-mode: standard
      margin-width: 250px  #right side margin width
      body-width: 1400px  #controls the width of the area where I content goes - change this in 501

include-in-header: cookies.html
include-after-body: tocFixer.html

number-sections: true
number-depth: 3
toc-depth: 4
crossref:
  chapters: true
  fig-title: Fig
  def-title: "Def."

#how to make custom numbering for various items
  custom:
    - kind: float
      reference-prefix: Video
      key: vid
      caption-location: top
    - kind: float
      reference-prefix: Rcode
      key: rcd

editor: visual
license: "CC-BY-NC"

comments:
  hypothesis: false  #change to true if we want it


